export default {
    CART_AMOUNT_INCREASE = "CART_AMOUNT_INCREASE",
    CART_AMOUNT_DECREASE = "CART_AMOUNT_DECREASE",
    ADD_TODO = "ADD_TODO",
    TOGGLE_TODO = "TOGGLE_TODO",
    SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER",
}